spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mapping_relations?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: password

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
      show-sql: true



logging:
  level:
    root: INFO
    hibernate: DEBUG

server:
  port: 8080
